name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'RELEASE_V*'

permissions:
  contents: write
  packages: write

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - name: Set up Qt (macOS)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0-${{ matrix.arch }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (macOS ${{ matrix.arch }})
        run: |
          # Set the target architecture in CMakeLists.txt
          sed -i '' 's/set(CMAKE_OSX_ARCHITECTURES.*/set(CMAKE_OSX_ARCHITECTURES "${{ matrix.arch }}")/' CMakeLists.txt
          chmod +x ./build.sh
          ./build.sh
      - name: Rename app for architecture
        run: |
          # Rename the app to include architecture
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            mv build/MonitorSwitch.app build/MonitorSwitch-ARM.app
          else
            mv build/MonitorSwitch.app build/MonitorSwitch-Intel.app
          fi
      - name: Sign macOS app (ad-hoc)
        run: |
          # Determine app name based on architecture
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            APP_NAME="MonitorSwitch-ARM.app"
          else
            APP_NAME="MonitorSwitch-Intel.app"
          fi
          
          # Ad-hoc sign the app bundle with free certificate
          # This allows the app to run without requiring a paid Apple Developer certificate
          echo "Signing $APP_NAME with ad-hoc certificate..."
          codesign --force --deep --sign - build/$APP_NAME
          
          # Verify the signature
          echo "Verifying app signature..."
          codesign --verify --verbose=2 build/$APP_NAME
          
          # Display signature information
          echo "App signature details:"
          codesign --display --verbose=4 build/$APP_NAME
          
          # Test that the app is properly signed
          echo "Testing app signature validity..."
          spctl --assess --type exec build/$APP_NAME || echo "Note: App assessment failed (expected for ad-hoc signed apps)"
          
          # Verify app bundle is still intact after signing
          echo "App bundle after signing:"
          ls -la build/$APP_NAME/Contents/MacOS/
          file build/$APP_NAME/Contents/MacOS/MonitorSwitch
      - name: Create ZIP package
        run: |
          # Determine app and package names based on architecture
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            APP_NAME="MonitorSwitch-ARM.app"
            PACKAGE_NAME="MonitorSwitch-macOS-ARM"
          else
            APP_NAME="MonitorSwitch-Intel.app"
            PACKAGE_NAME="MonitorSwitch-macOS-Intel"
          fi
          
          # Create a temporary directory for packaging
          mkdir -p macos_package
          cp -R build/$APP_NAME macos_package/
          
          # Create installation instructions
          cat > macos_package/INSTALL.txt << EOF
          MonitorSwitch Installation Instructions (${{ matrix.arch }})
          =============================================
          
          IMPORTANT: This app is ad-hoc signed (free certificate) for distribution.
          Architecture: ${{ matrix.arch }}
          
          To install and run the app:
          1. Copy $APP_NAME to your Applications folder
          2. Right-click on $APP_NAME and select "Open"
          3. Click "Open" when macOS asks for confirmation
          4. The app will then run normally from future launches
          
          If you see security warnings:
          - Go to System Preferences > Security & Privacy > General
          - Click "Open Anyway" when you see the MonitorSwitch notification
          
          Note: These security warnings are expected for apps not distributed 
          through the Mac App Store.
          
          Architecture Notes:
          - ARM version: For Apple Silicon Macs (M1, M2, M3, etc.)
          - Intel version: For Intel-based Macs
          EOF
          
          # Create the ZIP file
          cd macos_package
          zip -r ../build/${PACKAGE_NAME}.zip .
          cd ..
          
          # Verify the ZIP was created
          ls -la build/${PACKAGE_NAME}.zip
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-macOS-${{ matrix.arch }}
          path: build/MonitorSwitch-macOS-${{ matrix.arch == 'arm64' && 'ARM' || 'Intel' }}.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set up Qt (Windows)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (Windows)
        run: |
          # Create build directory
          mkdir build
          cd build
          
          # Configure with CMake using Visual Studio generator
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release ..
          
          # Build the project
          cmake --build . --config Release
          
      - name: Deploy Qt libraries (Windows)
        run: |
          # Create deployment directory
          mkdir deploy
          
          # Copy executable to deployment directory
          copy build\Release\MonitorSwitch.exe deploy\
          
          # Use windeployqt to bundle Qt libraries
          windeployqt.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw deploy\MonitorSwitch.exe
          
          # Copy icons to deployment directory
          mkdir deploy\icons
          copy icons\MonitorSwitch.ico deploy\icons\
          copy icons\MonitorSwitch.png deploy\icons\
          copy icons\MonitorSwitch_icon.svg deploy\icons\
          
      - name: Create Windows Installer
        run: |
          # Install Inno Setup
          choco install innosetup -y
          
          # Create installer output directory
          mkdir installer_output
          
          # Compile the installer
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" MonitorSwitch.iss
          
          # Verify installer was created
          ls installer_output\
          
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-Windows-Setup
          path: installer_output\MonitorSwitch-Setup.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qt (Linux)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libx11-dev libudev-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (Linux)
        run: |
          pwd
          ls -la ./src/
          chmod +x ./build.sh
          ./build.sh
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-Linux
          path: build/MonitorSwitch

  release:
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'release' && github.event.action == 'created')
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Use the tag name as the release name
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # Set to true for prerelease, false for final release
          prerelease: false
          # Path to files to attach to the release
          files: |
            artifacts/MonitorSwitch-macOS-ARM.zip
            artifacts/MonitorSwitch-macOS-Intel.zip
            artifacts/MonitorSwitch-Setup.exe
            artifacts/MonitorSwitch
