name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'RELEASE_V*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Qt (macOS)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (macOS)
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-macOS
          path: build/MonitorSwitch.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set up Qt (Windows)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (Windows)
        run: |
          .\build.bat
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-Windows
          path: build/MonitorSwitch.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qt (Linux)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt-6.5.0
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libx11-dev libudev-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build (Linux)
        run: |
          pwd
          ls -la ./src/
          chmod +x ./build.sh
          ./build.sh
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonitorSwitch-Linux
          path: build/MonitorSwitch

  release:
    if: startsWith(github.ref, 'refs/tags/RELASE_V')
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: MonitorSwitch-macOS
          path: ./artifacts
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: MonitorSwitch-Windows
          path: ./artifacts
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: MonitorSwitch-Linux
          path: ./artifacts
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF_NAME#RELASE_}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.version }}
          files: |
            artifacts/MonitorSwitch.app
            artifacts/MonitorSwitch.exe
            artifacts/MonitorSwitch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
